title: "Albert Tugushev"
description: "Albert Tugushev's personal website"
baseurl: "/"
url: "https://www.tugushev.ru"

header_pages:
  - index.md
  - projects.md
  - about.md
  - contact.md

style: light

footer: "© Copyright 2023 by Albert Tugushev.<style>p {margin-bottom: 15px;}</style>"

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
