title: "Cow house"
description: "A big cow house"
baseurl: "/"
url: "https://tugushev.ru"

header_pages:
  - index.md
  - about.md
  - contact.md

style: light

footer: 'follow me on <a href="https://twitter.com/metalikus">twitter</a>'

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
